version: '3'
services:
  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root12345
      - MYSQL_DATABASE=test
      - MYSQL_USER=karan
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  registration-login:
    image: karan1296/pipeline_1296/Registration:latest
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8081:8080
    command: mvn clean spring-boot:run
    depends_on:
      - myapp-mysql
